### ISSUE TITLE
Support creating a string from a single character

### ISSUE THREAD

**Issue by beweedon** [microsoft/Microsoft-UI-UIAutomation#64]
I don't think this would be possible in the wrappers. We'd need a new instruction, or potentially a modification to NewString which accepts a character. I think the former is the way to go, since modifying existing instructions doesn't really fit into our versioning model.

There's definitely also an argument that this isn't necessary, since someone could write their bytecode to deal in single-character strings, rather than actual character types. It's worth some discussion.

Thanks @mavangur for bringing this up.

**Comment by mavangur** [comment]
Sure Ben. No problem :)

**Comment by mlalic** [comment]
@beweedon  This is already possible. See #34 (you can find the matching platform instruction implementation based on that).

**Comment by beweedon** [comment]
Oh yeah, good point. I didn't think of Stringify for this specific case. I'll close this.
