### ISSUE TITLE
Custom patterns are impossible in c#

### ISSUE THREAD

**Issue by betty-crokker** [microsoft/Microsoft-UI-UIAutomation#96]
There are a lot of problems with custom patterns in c# (WPF).

1)  IUIAutomationRegistrar.RegisterPattern() gets imported incorrectly.  
The c++ signature is 
```
 HRESULT RegisterPattern(
   [in]  const UIAutomationPatternInfo *pattern,
   [out] PATTERNID                     *pPatternId,
   [out] PROPERTYID                    *pPatternAvailablePropertyId,
   [in]  UINT                          propertyIdCount,
   [out] PROPERTYID                    *pPropertyIds,
   [in]  UINT                          eventIdCount,
   [out] EVENTID                       *pEventIds
 );

```
but when imported into c#, the PROPERTYID arrays are wrong:
```
void RegisterPattern([In] ref UIAutomationPatternInfo pattern,
    out int pPatternId, out int pPatternAvailablePropertyId,
    [In] uint propertyIdCount, out int pPropertyIds,
    [In] uint eventIdCount, out int pEventIds);

```
See https://docs.microsoft.com/en-us/answers/questions/889043/how-can-i-34fix34-a-mis-imported-com-interface-cwp.html

2) I got around (1) by doing the RegisterPattern() in a c++ DLL that I included in my project, but even when I call GetCurrentPattern() on the registered pattern ID (from my c# automated UI test harness), it returns a null, and I've got a bunch of logging in the c# application being tested, and as far as I can tell the call to GetCurrentPattern() failed inside the test harness (no communication made to the application being tested)

3) Even if I can get GetCurrentPattern() to work in the test harness, the GetPattern() override in the application being tested has a single parameter which is an enum PatternInterface so it's not really able to pass my custom pattern ID.

Should I create these as separate issues?  Or is UIAutomation/c# not a supported combination?

**Comment by rahulkhanna1605** [comment]
Hi @betty-crokker, could you please provide some more info about the issue:

1. How are you translating from the result of RegisterPattern in C++ to your C# code?
2. What HRESULT is GetCurrentPattern returning when it fails?
3. Could you go into more detail on the GetPattern override in the tested application? Do you have any control over the implementation of that application? Are you trying to register a custom pattern that the application doesn't support?
